# DEFAULT SETTINGS
# user:
#   username: default_user

# configuration:
#   pomodore_time: 25
#   short_rest_time: 5
#   long_rest_time: 15
#   number_of_rounds: 4

user:
  username: default_user

configuration:
  pomodore_time: 25
  short_rest_time: 5
  long_rest_time: 15
  number_of_rounds: 4